

hand_link = {"allegro":[
    "palm",
    "link_0",
    "link_4",
    "link_8",
    "link_12",
    "wrist",
    "link_1",
    "link_5",
    "link_9",
    "link_13",
    "link_2",
    "link_6",
    "link_10",
    "link_14",
    "link_3",
    "link_7",
    "link_11",
    "link_15",
    "link_3_tip",
    "link_7_tip",
    "link_11_tip",
    "link_15_tip",
    "thumb_tip_head", "index_tip_head", "middle_tip_head", "ring_tip_head",
],
"shadow":[
    "palm",
    'thtip', 'fftip', 'mftip', 'rftip', 'lftip',
    'thbase', 'thhub',
    'thproximal', 'ffproximal', 'mfproximal', 'rfproximal', 'lfproximal',
    'thmiddle', 'ffmiddle', 'mfmiddle', 'rfmiddle', 'lfmiddle',
    'thdistal', 'ffdistal', 'mfdistal', 'rfdistal', 
    'fftip', 'mftip', 'rftip', 'lfdistal','lftip'   
],
"leap":[
    'pip',
    'pip_2',
    'pip_3',
    'thumb_pip',
    'dip',
    'dip_2',
    'dip_3',
    'thumb_dip',
    'fingertip',
    'fingertip_2',
    'fingertip_3',
    'thumb_fingertip',
    'palm_lower',
    'mcp_joint',
    'mcp_joint_2',
    'mcp_joint_3',
    'thumb_temp_base',    
]
}