sapien_joint = { "ur5e_allegro_right":['shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint', 'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint', 
                                       'joint_0', 'joint_4', 'joint_8', 'joint_12', 'joint_1', 'joint_5', 'joint_9', 'joint_13', 'joint_2', 'joint_6', 'joint_10', 'joint_14', 'joint_3', 'joint_7', 'joint_11', 'joint_15'],
                 "xarm6_shadow_right":['joint1', 'joint2', 'joint3', 'joint4', 'joint5', 'joint6', 
                                       'WRJ2', 'WRJ1', 'FFJ4', 'MFJ4', 'RFJ4', 'LFJ5', 'THJ5', 'FFJ3', 'MFJ3', 'RFJ3', 'LFJ4', 'THJ4', 'FFJ2', 'MFJ2', 'RFJ2', 'LFJ3', 'THJ3', 'FFJ1', 'MFJ1', 'RFJ1', 'LFJ2', 'THJ2', 'LFJ1', 'THJ1'],
                 "xarm7_leap_right": ['joint1', 'joint2', 'joint3', 'joint4', 'joint5', 'joint6', 'joint7', 
                                      '1', '5', '9', '12', '0', '4', '8', '13', '2', '6', '10', '14', '3', '7', '11', '15']
}

hand_link = {"allegro":[
    "base_link_hand",
    "link_0",
    "link_4",
    "link_8",
    "link_12",
    "wrist",
    "link_1",
    "link_5",
    "link_9",
    "link_13",
    "link_2",
    "link_6",
    "link_10",
    "link_14",
    "link_3",
    "link_7",
    "link_11",
    "link_15",
    "link_3_tip",
    "link_7_tip",
    "link_11_tip",
    "link_15_tip",
],
"shadow":[
    "wrist","palm",
    'thtip', 'fftip', 'mftip', 'rftip', 'lftip',
    'thbase', 'thhub', 'lfmetacarpal',
    'thproximal', 'ffproximal', 'mfproximal', 'rfproximal', 'lfproximal',
    'thmiddle', 'ffmiddle', 'mfmiddle', 'rfmiddle', 'lfmiddle',
    'thdistal', 'ffdistal', 'mfdistal', 'rfdistal', 
    'ffknuckle', 'mfknuckle', 'rfknuckle', 'lfknuckle',   
],
"leap":[
    'palm_lower',
    'pip',
    'pip_2',
    'pip_3',
    'thumb_pip',
    'dip',
    'dip_2',
    'dip_3',
    'thumb_dip',
    'fingertip',
    'fingertip_2',
    'fingertip_3',
    'thumb_fingertip',
    'palm_lower',
    'mcp_joint',
    'mcp_joint_2',
    'mcp_joint_3',
    'thumb_temp_base',    
]
}